Repository boring-km/k-stock, pull requests merged in 2021-04, with the labels that each got.

#22 [KS-SER-06-km] stock-core 설계 변경
  server/stock-api/src/main/kotlin/study/kstock/stockapi/controller/StockServiceController.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/message/ResponseFactory.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/service/StockService.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/controller/APIController.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/message/ApiRequest.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/message/KafkaDataMap.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/message/ResponseFactory.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/model/Commander.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/model/StockData.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/model/StockMarket.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/model/StockSymbol.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/CommandMappingService.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/KafkaReceiveService.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/StockService.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/save/StockDataSaving.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/save/StockSavingService.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/save/StockSymbolSaving.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/search/MarketListByRegionSearching.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/search/StockSearchingService.kt
  server/stock-core/src/main/kotlin/study/kstock/stockcore/service/search/TwentyStockDataSearching.kt
  server/stock-core/src/test/kotlin/study/kstock/stockcore/service/KafkaExecuteServiceTest.kt
  server/stock-core/src/test/kotlin/study/kstock/stockcore/service/StockServiceTest.kt
Labels: 👏 기능 추가 👏

#26 KS-SER-06-jb
  server/stock-external/src/main/kotlin/study/kstock/stockexternal/domain/StockData.kt
  server/stock-external/src/main/kotlin/study/kstock/stockexternal/domain/StockMarket.kt
  server/stock-external/src/main/kotlin/study/kstock/stockexternal/domain/StockSymbol.kt
  server/stock-external/src/main/kotlin/study/kstock/stockexternal/service/StockPriceService.kt
  server/stock-external/src/test/kotlin/study/kstock/stockexternal/service/StockPriceGetTest.kt
Labels: 👀 틀린것 같음, 👏 기능 추가 👏

#28 [KS-SER-07-km] 주식 조회를 stock-api 에서 크롤링 한다.
  server/stock-api/build.gradle.kts
  server/stock-api/src/main/kotlin/study/kstock/stockapi/controller/GetStockDirectlyController.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/controller/StockServiceController.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/domain/StockData.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/domain/StockMarket.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/domain/StockSymbol.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/message/ResponseFactory.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/service/StockDataCrawlingService.kt
  server/stock-api/src/test/kotlin/study/kstock/stockapi/service/StockDataCrawlingServiceTest.kt
Labels: 중복, 👏 기능 추가 👏

#29 [KS-SER-07-km] 주식 데이터 20개씩 조회 API 수정
  server/stock-api/src/main/kotlin/study/kstock/stockapi/controller/GetStockDirectlyController.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/service/StockDataCrawlingService.kt
Labels: 👀 틀린것 같음

#32 [KS-APP-03] 미완성 개발 부분 정리
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/study/kstockapp/MainActivity.kt
  android/app/src/main/java/study/kstockapp/StockAdapter.kt
  android/app/src/main/java/study/kstockapp/StockData.kt
  android/app/src/main/java/study/kstockapp/StockDetail.kt
  android/app/src/main/java/study/kstockapp/domain/StockData.kt
  android/app/src/main/java/study/kstockapp/domain/StockMarket.kt
  android/app/src/main/java/study/kstockapp/domain/StockSymbol.kt
  android/app/src/main/java/study/kstockapp/network/KStockService.kt
  android/app/src/main/java/study/kstockapp/network/RetrofitClient.kt
  android/app/src/main/java/study/kstockapp/service/KStockServiceComponent.kt
  android/app/src/main/java/study/kstockapp/service/KStockServiceImpl.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/card_layout.xml
  android/app/src/main/res/values/arrays.xml
  android/app/src/test/java/study/kstockapp/RetrofitTest.kt
Labels: 버그

#31 [KS-SER-08-km] 주식 호출 시 Redis Cache 사용
  server/stock-api/build.gradle.kts
  server/stock-api/src/main/kotlin/study/kstock/stockapi/config/CacheConfig.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/domain/StockData.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/domain/StockMarket.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/domain/StockSymbol.kt
  server/stock-api/src/main/kotlin/study/kstock/stockapi/service/StockDataCrawlingService.kt
  server/stock-api/src/main/resources/application.properties
  server/stock-api/src/test/kotlin/study/kstock/stockapi/service/StockServiceTest.kt
Labels: 🆘 도움이 필요함, 👏 기능 추가 👏
